apiVersion: v1
kind: Service
metadata:
  name: flask-canary-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-canary # ⬅️ This is the key. It selects ALL pods managed by both deployments.
