apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-canary
  annotations:
    harness.io/skip-versioning: "true"
spec:
  replicas: 3 # You can use a different number here for canary
  template:
    metadata:
      labels:
        app: flask-canary
    spec:
      containers:
      - name: flask-container
        image: your-docker-registry/flask-canary:2.0.0
        ports:
        - containerPort: 5000
